import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { format, resolveConfig } from 'prettier';
import { remark } from 'remark';
import remarkHtml from 'remark-html';

const rootDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const postsDirectory = path.join(rootDirectory, 'posts');
const outputPath = path.join(rootDirectory, 'app/data/posts.generated.ts');

let fileNames = (await fs.readdir(postsDirectory)).filter((fileName) => fileName.endsWith('.md'));

let posts = await Promise.all(
	fileNames.map(async (fileName) => {
		let id = fileName.replace(/\.md$/, '');
		let filePath = path.join(postsDirectory, fileName);
		let source = await fs.readFile(filePath, 'utf8');
		let { content, data } = matter(source);
		let { date, title } = readMetadata(data, filePath);
		let html = String(await remark().use(remarkHtml).process(content));

		return { id, date, title, html };
	})
);

posts.sort((a, b) => (a.date < b.date ? 1 : -1));

let output = `// Generated by npm run build. Do not edit.\n\n`;
output += `export const posts = ${JSON.stringify(posts, null, '\t')} as const;\n`;
let prettierConfig = await resolveConfig(outputPath);
await fs.writeFile(outputPath, await format(output, { ...prettierConfig, filepath: outputPath }));

function readMetadata(data: Record<string, unknown>, filePath: string) {
	let { date, title } = data;
	if (!date || typeof date !== 'string') throw new Error(`Missing date in ${filePath}`);
	if (!title || typeof title !== 'string') throw new Error(`Missing title in ${filePath}`);
	return { date, title };
}
